import sys
content = '<?xml version="1.0" encoding="utf-8"?>\n'
content += '<ResourceDictionary\n'
content += '    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"\n'
content += '    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"\n'
content += '    xmlns:converters="using:iscWBS.Converters">\n'
content += '    <converters:BoolToVisibilityConverter x:Key="BoolToVisibilityConverter" />\n'
content += '    <ResourceDictionary.ThemeDictionaries>\n'
content += '        <ResourceDictionary x:Key="Light">\n'
content += '            <SolidColorBrush x:Key="WbsStatusNotStartedBrush" Color="#808080" />\n'
content += '            <SolidColorBrush x:Key="WbsStatusInProgressBrush" Color="#0078D4" />\n'
content += '            <SolidColorBrush x:Key="WbsStatusCompleteBrush"   Color="#107C10" />\n'
content += '            <SolidColorBrush x:Key="WbsStatusBlockedBrush"    Color="#C50F1F" />\n'
content += '        </ResourceDictionary>\n'
content += '        <ResourceDictionary x:Key="Dark">\n'
content += '            <SolidColorBrush x:Key="WbsStatusNotStartedBrush" Color="#9E9E9E" />\n'
content += '            <SolidColorBrush x:Key="WbsStatusInProgressBrush" Color="#60CDFF" />\n'
content += '            <SolidColorBrush x:Key="WbsStatusCompleteBrush"   Color="#6CCB5F" />\n'
content += '            <SolidColorBrush x:Key="WbsStatusBlockedBrush"    Color="#FF99A4" />\n'
content += '        </ResourceDictionary>\n'
content += '        <ResourceDictionary x:Key="HighContrast">\n'
content += '            <SolidColorBrush x:Key="WbsStatusNotStartedBrush" Color="{ThemeResource SystemColorWindowTextColor}" />\n'
content += '            <SolidColorBrush x:Key="WbsStatusInProgressBrush" Color="{ThemeResource SystemColorHighlightColor}" />\n'
content += '            <SolidColorBrush x:Key="WbsStatusCompleteBrush"   Color="{ThemeResource SystemColorWindowTextColor}" />\n'
content += '            <SolidColorBrush x:Key="WbsStatusBlockedBrush"    Color="{ThemeResource SystemColorHighlightTextColor}" />\n'
content += '        </ResourceDictionary>\n'
content += '    </ResourceDictionary.ThemeDictionaries>\n'
content += '</ResourceDictionary>\n'
with open('Themes/Generic.xaml', 'w', encoding='utf-8') as f:
    f.write(content)
print('OK')
